-- Employee Analysis:

-- Which employee, along with their job title, supports the highest number of customers?
SELECT E.EmployeeId,
	E.FirstName,
	E.LastName,
	E.Title,
	COUNT(C.CustomerId)  AS 'Number Of Customers'
FROM Employee E
LEFT OUTER JOIN Customer C
ON E.EmployeeId = C.SupportRepId
GROUP BY E.EmployeeId , E.FirstName , E.LastName , E.Title
ORDER BY [Number Of Customers] DESC;


--List all employees with their job titles, showing the number of invoices generated by their supported customers, including employees with zero invoices
SELECT E.EmployeeId, 
	E.FirstName,
	E.LastName,
	E.Title,
	COUNT(I.InvoiceId) AS 'Number Of Invoices'
FROM Employee E
LEFT OUTER JOIN Customer C
ON E.EmployeeId = C.SupportRepId
LEFT OUTER JOIN Invoice I
ON C.CustomerId = I.CustomerId
GROUP BY E.EmployeeId , E.FirstName , E.LastName ,E.Title
ORDER BY [Number Of Invoices] DESC;

--Which employee ,along with their job title, supports customers who generate the highest total revenue (profit)
SELECT E.EmployeeId,
	E.FirstName,
	E.LastName,
	E.Title,
	ISNULL(SUM(I.Total) , 0) AS 'Profit'
FROM Employee E
LEFT OUTER JOIN Customer C
ON E.EmployeeId = C.SupportRepId
LEFT OUTER JOIN Invoice I 
ON C.CustomerId = I.CustomerId
GROUP BY E.EmployeeId , E.FirstName ,E.LastName , E.Title
ORDER BY Profit DESC;

-- Which employee has the highest annual impact (performance) based on profits?
SELECT YEAR(I.InvoiceDate) AS Year, 
	E.EmployeeId,
	E.FirstName,
	E.LastName,
	E.Title,
	ISNULL(SUM(I.Total) , 0) AS 'Profit'
FROM Employee E
LEFT OUTER JOIN Customer C
ON E.EmployeeId = C.SupportRepId
LEFT OUTER JOIN Invoice I 
ON C.CustomerId = I.CustomerId
GROUP BY YEAR(I.InvoiceDate) ,E.EmployeeId , E.FirstName ,E.LastName , E.Title
ORDER BY Year Desc,Profit DESC;


